name: Update loffice-365

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  update:
    name: Update loffice-365
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install
          
          NATIVEFIER_VERSION=$(npm view nativefier version)
          echo "NATIVEFIER_VERSION=$NATIVEFIER_VERSION" >> $GITHUB_ENV

      - name: Build
        run: |
          npm run build

      - name: Upload binaries/loffice-365.tgz
        uses: actions/upload-artifact@v3
        with:
          name: loffice-365.tgz
          path: binaries/loffice-365.tgz

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/loffice-365.tgz
